# Trabalho 3

## Configuração do ambiente

Para este trabalho será utilizada a base de dados da FAPESP (fapcov2103). As instruções para carregamento da base estão disponíveis no Moodle da disciplina e requerem ajustes finos de caminhos de arquivo para execução local.

In [21]:
# Valida carregamento da base
%load_ext sql
import pandas.io.sql as pdsql
import pandas as pd
from sqlalchemy import create_engine, text

# Credenciais de execução local, ajuste para sua propria maquina
engine = create_engine('postgresql://myuser:mysecretpassword@localhost/fapcov2103')
conn = engine.connect()

query = text("""
    SELECT 'Pacientes' AS tabela, Count(*) FROM d2.pacientes
    UNION ALL
    SELECT 'ExamLabs', Count(*) FROM d2.examlabs
    UNION ALL
    SELECT 'Desfechos', Count(*) FROM d2.desfechos;
""")
pdsql.read_sql(query, conn)

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

      tabela    count
0  Pacientes    53673
1   ExamLabs  8292292
2  Desfechos   307928


## Enunciado:

<table style="margin-left: 0; width: 800px;">
    <tr><td style="border: 2px solid #4DD0E1; background-color: #B2EBF2;">
        <font face="Georgia", size="4", color=#006064> 
    Listar a contagem de quantos Exames de Coronavírus foram feitos<br>
        (procurar 'corona' ou 'covid'), contabilizando:<ul>
  <li> Pelos diferentes tipos de exame, separados por hospital,
  <li> Quantos foram feitos por pacientes de cada cidade, também separados por hospital.
  <li> Cuidado para identificar corretamente os atributos que estejam nulos em cada tupla <br>
         &emsp; &emsp; (Tratar os <code>Nulos</code> devido aos valores originais ou aos gerados pelo <code>GROUP BY</code>).
  </ul>
     &emsp;  <font size="5">&#128073;&#127997;</font>A atividade deve ser executada em SQL.</font>
</font>
    </td></tr>
</table>    
<br>
<hr style="height:10px; width:650pt; color:#008EBD; background-color:#008EBD; margin-left:0"> 
<br>

# Problema

Existem dois requisitos diferentes pelo enunciado

1. Enumerar quantidade de exames por tipo de exame e hospital
2. Enumerar quantidade de exame por cidade, por hospital

Ambas podem ser realizadas por um GROUP BY com GROUPING SETS, utilizando COUNT como método de agregação

# Solução 1

Nesta solução, os dois requisitos foram realizados, sem uma visão geral de cada hospital.

## Como foi feito

### GROUP BY com GROUPING SETS

O enunciado pede duas contagens na mesma consulta: por tipo de exame + hospital e por cidade + hospital. Um `GROUP BY` com `GROUPING SETS` permite declarar os dois conjuntos de agrupamento e resolver tudo em uma única leitura da tabela:

- `(E.De_Hospital, E.De_Exame)`: quantidade de exames de covid/corona de cada tipo de exame em cada hospital;
- `(E.De_Hospital, COALESCE(P.CD_Municipio, 'Não informado'))`: quantidade por cidade de residência do paciente em cada hospital.

A agregação é `Count(*)`, contando as linhas de `ExamLabs` que caem em cada grupo.

### Condição com corona ou covid

A seleção é feita no `WHERE`, antes do agrupamento, com expressão regular case-insensitive:

- `E.De_Exame ~* 'corona|covid'` casa `corona`, `Corona`, `coronavírus`, `covid`, `COVID-19` etc.;
- como o filtro é aplicado antes do `GROUP BY`, as duas visões contam apenas exames de covid/corona.

### Tratamento de valores faltantes e NULLS gerados pela agregação

- Faltantes originais: pacientes sem município (`CD_Municipio IS NULL`) sairiam como `NULL`; usamos `COALESCE` para dar um rótulo explícito.
- NULLs da agregação: em `GROUPING SETS`, as colunas que não fazem parte do conjunto da vez saem `NULL`. Para diferenciar "não se aplica" de valor faltante, usamos `GROUPING(col)`, que retorna `1` quando a coluna não está no conjunto corrente, e rotulamos com `'Todos'` via `CASE WHEN GROUPING(...) = 1 ...`.
- A ordenação `ORDER BY E.De_Hospital, GROUPING(E.De_Exame), quantidade DESC` coloca, em cada hospital, as linhas de tipo de exame antes das de cidade, e dentro de cada bloco as maiores quantidades primeiro.

In [22]:
consulta_exames_covid = text("""
    SELECT COALESCE(E.De_Hospital, 'Todos') AS hospital,
           CASE WHEN GROUPING(E.De_Exame) = 1 THEN 'Todos' ELSE E.De_Exame END AS tipo_de_exame,
           CASE WHEN GROUPING(COALESCE(P.CD_Municipio, 'Não informado')) = 1 THEN 'Todos'
                ELSE COALESCE(P.CD_Municipio, 'Não informado') END AS cidade,
           Count(*) AS quantidade
        FROM D2.ExamLabs E LEFT JOIN D2.Pacientes P
            ON P.ID_Paciente = E.ID_Paciente
        WHERE E.De_Exame ~* 'corona|covid'
        GROUP BY GROUPING SETS (
            (E.De_Hospital, E.De_Exame),
            (E.De_Hospital, COALESCE(P.CD_Municipio, 'Não informado'))
        )
        ORDER BY E.De_Hospital, GROUPING(E.De_Exame), quantidade DESC;
""")

display(pdsql.read_sql(consulta_exames_covid, conn))

,hospital,tipo_de_exame,cidade,quantidade
0,BPSP,coronavírus covid-19,Todos,33986
1,BPSP,coronavírus covid-19 - pre cirurgico,Todos,6258
2,BPSP,"sorologia para trial - coronavírus, igg",Todos,72
3,BPSP,"sorologia para trial - coronavírus, iga",Todos,70
4,BPSP,coronavírus covid-19 - coalizao vi - inativo,Todos,41
5,BPSP,Todos,SAO PAULO,30444
6,BPSP,Todos,Não informado,8272
7,BPSP,Todos,GUARULHOS,806
8,BPSP,Todos,OSASCO,490
9,BPSP,Todos,MOGI DAS CRUZES,101
10,BPSP,Todos,SAO BERNARDO DO CAMPO,73
11,BPSP,Todos,SUZANO,46
12,BPSP,Todos,SANTO ANDRE,41
13,BPSP,Todos,COTIA,38
14,BPSP,Todos,BARUERI,37
15,BPSP,Todos,DIADEMA,33
16,BPSP,Todos,SANTOS,26
17,BPSP,Todos,CARAPICUIBA,10
18,BPSP,Todos,MANAUS,6
19,BPSP,Todos,SANTANA DE PARNAIBA,4
20,HSL,"covid-19-pcr para sars-cov-2, vários materiais...",Todos,16206
21,HSL,covid-19-sorologia igm e igg por quimiluminesc...,Todos,11196
22,HSL,detecção de coronavírus (ncov-2019) por pcr (a...,Todos,10614
23,HSL,"covid-19-teste rápido (igm e igg), soro",Todos,515
24,HSL,"sorologia - coronavírus, igg",Todos,304
25,HSL,"sorologia - coronavírus, iga",Todos,242
26,HSL,"covid-19, anticorpos iga e igg, soro",Todos,30
27,HSL,Todos,SAO PAULO,24313
28,HSL,Todos,Não informado,10068
29,HSL,Todos,BRASILIA,4076
30,HSL,Todos,GUARULHOS,427
31,HSL,Todos,OSASCO,96
32,HSL,Todos,CAMPOS DO JORDAO,46
33,HSL,Todos,BELEM,30
34,HSL,Todos,SAO BERNARDO DO CAMPO,29
35,HSL,Todos,DIADEMA,12
36,HSL,Todos,MOGI DAS CRUZES,10

# Solução 2

Para esta solução também foi realizada a visão geral de cada hospital, subindo a granularidade utilizando uma consulta ROLLUP

## O que mudou

Da Solução 1 para a Solução 2:

- a visão por tipo de exame virou um `ROLLUP(E.De_Hospital, E.De_Exame)`, acrescentando o total de cada hospital e o total geral (conjuntos `(hospital)` e `()`);
- a visão por cidade também virou um `ROLLUP(E.De_Hospital, COALESCE(P.CD_Municipio, 'Não informado'))`; com ROLLUP nas duas listas, os conjuntos `(hospital)` e `()` passam a ser gerados duas vezes, duplicando os subtotais e o total geral;
- o `SELECT DISTINCT` na subconsulta remove essas repetições (de 43 para 40 linhas), pois as cópias têm os mesmos valores exibidos e as mesmas flags de agrupamento;
- o Postgres exige que expressões do `ORDER BY` de um `SELECT DISTINCT` apareçam na lista de seleção; por isso os `GROUPING(...)` (`g_hospital`, `g_tipo`, `g_cidade`) são calculados na subconsulta e usados para ordenar, e a consulta externa projeta apenas `hospital`, `tipo_de_exame`, `cidade` e `quantidade`;

In [23]:
consulta_exames_covid_rollup = text("""
    SELECT hospital, tipo_de_exame, cidade, quantidade
        FROM (
            SELECT DISTINCT
                   COALESCE(E.De_Hospital, 'Todos') AS hospital,
                   CASE WHEN GROUPING(E.De_Exame) = 1 THEN 'Todos' ELSE E.De_Exame END AS tipo_de_exame,
                   CASE WHEN GROUPING(COALESCE(P.CD_Municipio, 'Não informado')) = 1 THEN 'Todos'
                        ELSE COALESCE(P.CD_Municipio, 'Não informado') END AS cidade,
                   Count(*) AS quantidade,
                   GROUPING(E.De_Hospital) AS g_hospital,
                   GROUPING(E.De_Exame) AS g_tipo,
                   GROUPING(COALESCE(P.CD_Municipio, 'Não informado')) AS g_cidade
                FROM D2.ExamLabs E LEFT JOIN D2.Pacientes P
                    ON P.ID_Paciente = E.ID_Paciente
                WHERE E.De_Exame ~* 'corona|covid'
                GROUP BY GROUPING SETS (
                    ROLLUP(E.De_Hospital, E.De_Exame),
                    ROLLUP(E.De_Hospital, COALESCE(P.CD_Municipio, 'Não informado'))
                )
        ) AS t
        ORDER BY g_hospital, hospital, g_tipo, g_cidade, quantidade DESC;
""")

display(pdsql.read_sql(consulta_exames_covid_rollup, conn))

,hospital,tipo_de_exame,cidade,quantidade
0,BPSP,coronavírus covid-19,Todos,33986
1,BPSP,coronavírus covid-19 - pre cirurgico,Todos,6258
2,BPSP,"sorologia para trial - coronavírus, igg",Todos,72
3,BPSP,"sorologia para trial - coronavírus, iga",Todos,70
4,BPSP,coronavírus covid-19 - coalizao vi - inativo,Todos,41
5,BPSP,Todos,SAO PAULO,30444
6,BPSP,Todos,Não informado,8272
7,BPSP,Todos,GUARULHOS,806
8,BPSP,Todos,OSASCO,490
9,BPSP,Todos,MOGI DAS CRUZES,101
10,BPSP,Todos,SAO BERNARDO DO CAMPO,73
11,BPSP,Todos,SUZANO,46
12,BPSP,Todos,SANTO ANDRE,41
13,BPSP,Todos,COTIA,38
14,BPSP,Todos,BARUERI,37
15,BPSP,Todos,DIADEMA,33
16,BPSP,Todos,SANTOS,26
17,BPSP,Todos,CARAPICUIBA,10
18,BPSP,Todos,MANAUS,6
19,BPSP,Todos,SANTANA DE PARNAIBA,4
20,BPSP,Todos,Todos,40427
21,HSL,"covid-19-pcr para sars-cov-2, vários materiais...",Todos,16206
22,HSL,covid-19-sorologia igm e igg por quimiluminesc...,Todos,11196
23,HSL,detecção de coronavírus (ncov-2019) por pcr (a...,Todos,10614
24,HSL,"covid-19-teste rápido (igm e igg), soro",Todos,515
25,HSL,"sorologia - coronavírus, igg",Todos,304
26,HSL,"sorologia - coronavírus, iga",Todos,242
27,HSL,"covid-19, anticorpos iga e igg, soro",Todos,30
28,HSL,Todos,SAO PAULO,24313
29,HSL,Todos,Não informado,10068
30,HSL,Todos,BRASILIA,4076
31,HSL,Todos,GUARULHOS,427
32,HSL,Todos,OSASCO,96
33,HSL,Todos,CAMPOS DO JORDAO,46
34,HSL,Todos,BELEM,30
35,HSL,Todos,SAO BERNARDO DO CAMPO,29
36,HSL,Todos,DIADEMA,12
37,HSL,Todos,MOGI DAS CRUZES,10
38,HSL,Todos,Todos,39107
39,Todos,Todos,Todos,79534